export async function GET() {
  return new Response(
    `
      <?xml version="1.0" encoding="UTF-8" ?>
      <urlset
        xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"
      >
        <url>
            <loc>https://minhanewlife.com.br/</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/avalie</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/blog</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/contato</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/indique</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/servicos</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/onde-estamos</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/aplicativo</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/para-condominios</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/para-empresas</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/para-voce</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/parcerias</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/premios</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/privacidade</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/quem-somos</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/responsabilidade-social</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/planos</loc>
        </url>
        <url>
            <loc>https://minhanewlife.com.br/trabalhe-conosco</loc>
        </url>
      </urlset>`.trim(),
    {
      headers: {
        "Content-Type": "application/xml",
      },
    },
  );
}
